###
POST http://localhost:3001/api/users HTTP/1.1
Content-Type: application/json

{
    "fullname": "Tommy Eghan",
    "email": "tommy@email.com",
    "password": "123456"
}
###

POST http://localhost:3001/api/login HTTP/1.1
Content-Type: application/json

{
    "email": "tommy@email.com",
    "password": "123456"
}

###
POST http://localhost:3001/api/conversations HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRvbW15QGVtYWlsLmNvbSIsImlkIjoiNjU3ZDhiZjAwZWU0ZTdmYjgzNDNhZTc3IiwiaWF0IjoxNzAyNzU5MDE5fQ.41E3HuI3c9-POzO7oWvNr6Bt1M84WGhY-pV1E81xiTU

{
    "message": "Who is the author of Attack on Titans"
}